// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/chirag3003/go-backend-template/repository (interfaces: MediaRepository)
//
// Generated by this command:
//
//	mockgen -destination=mock/mock_media.go -package=mock github.com/chirag3003/go-backend-template/repository MediaRepository
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	models "github.com/chirag3003/go-backend-template/models"
	gomock "go.uber.org/mock/gomock"
)

// MockMediaRepository is a mock of MediaRepository interface.
type MockMediaRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMediaRepositoryMockRecorder
	isgomock struct{}
}

// MockMediaRepositoryMockRecorder is the mock recorder for MockMediaRepository.
type MockMediaRepositoryMockRecorder struct {
	mock *MockMediaRepository
}

// NewMockMediaRepository creates a new mock instance.
func NewMockMediaRepository(ctrl *gomock.Controller) *MockMediaRepository {
	mock := &MockMediaRepository{ctrl: ctrl}
	mock.recorder = &MockMediaRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMediaRepository) EXPECT() *MockMediaRepositoryMockRecorder {
	return m.recorder
}

// CreateMedia mocks base method.
func (m *MockMediaRepository) CreateMedia(ctx context.Context, media *models.Media) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMedia", ctx, media)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateMedia indicates an expected call of CreateMedia.
func (mr *MockMediaRepositoryMockRecorder) CreateMedia(ctx, media any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMedia", reflect.TypeOf((*MockMediaRepository)(nil).CreateMedia), ctx, media)
}

// GetMediaByID mocks base method.
func (m *MockMediaRepository) GetMediaByID(ctx context.Context, id int64) (*models.Media, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMediaByID", ctx, id)
	ret0, _ := ret[0].(*models.Media)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMediaByID indicates an expected call of GetMediaByID.
func (mr *MockMediaRepositoryMockRecorder) GetMediaByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMediaByID", reflect.TypeOf((*MockMediaRepository)(nil).GetMediaByID), ctx, id)
}

// GetMediaByKey mocks base method.
func (m *MockMediaRepository) GetMediaByKey(ctx context.Context, key string) (*models.Media, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMediaByKey", ctx, key)
	ret0, _ := ret[0].(*models.Media)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMediaByKey indicates an expected call of GetMediaByKey.
func (mr *MockMediaRepositoryMockRecorder) GetMediaByKey(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMediaByKey", reflect.TypeOf((*MockMediaRepository)(nil).GetMediaByKey), ctx, key)
}

// UpdateMedia mocks base method.
func (m *MockMediaRepository) UpdateMedia(ctx context.Context, media *models.Media) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMedia", ctx, media)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMedia indicates an expected call of UpdateMedia.
func (mr *MockMediaRepositoryMockRecorder) UpdateMedia(ctx, media any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMedia", reflect.TypeOf((*MockMediaRepository)(nil).UpdateMedia), ctx, media)
}
