// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/chirag3003/go-backend-template/repository (interfaces: LinkRepository)
//
// Generated by this command:
//
//	mockgen -destination=mock/mock_link.go -package=mock github.com/chirag3003/go-backend-template/repository LinkRepository
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	models "github.com/chirag3003/go-backend-template/models"
	gomock "go.uber.org/mock/gomock"
)

// MockLinkRepository is a mock of LinkRepository interface.
type MockLinkRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLinkRepositoryMockRecorder
	isgomock struct{}
}

// MockLinkRepositoryMockRecorder is the mock recorder for MockLinkRepository.
type MockLinkRepositoryMockRecorder struct {
	mock *MockLinkRepository
}

// NewMockLinkRepository creates a new mock instance.
func NewMockLinkRepository(ctrl *gomock.Controller) *MockLinkRepository {
	mock := &MockLinkRepository{ctrl: ctrl}
	mock.recorder = &MockLinkRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLinkRepository) EXPECT() *MockLinkRepositoryMockRecorder {
	return m.recorder
}

// AliasExists mocks base method.
func (m *MockLinkRepository) AliasExists(ctx context.Context, alias string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AliasExists", ctx, alias)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AliasExists indicates an expected call of AliasExists.
func (mr *MockLinkRepositoryMockRecorder) AliasExists(ctx, alias any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AliasExists", reflect.TypeOf((*MockLinkRepository)(nil).AliasExists), ctx, alias)
}

// CreateLink mocks base method.
func (m *MockLinkRepository) CreateLink(ctx context.Context, link *models.Link) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLink", ctx, link)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateLink indicates an expected call of CreateLink.
func (mr *MockLinkRepositoryMockRecorder) CreateLink(ctx, link any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLink", reflect.TypeOf((*MockLinkRepository)(nil).CreateLink), ctx, link)
}

// DeleteLink mocks base method.
func (m *MockLinkRepository) DeleteLink(ctx context.Context, id, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLink", ctx, id, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteLink indicates an expected call of DeleteLink.
func (mr *MockLinkRepositoryMockRecorder) DeleteLink(ctx, id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLink", reflect.TypeOf((*MockLinkRepository)(nil).DeleteLink), ctx, id, userID)
}

// GetLinkByCode mocks base method.
func (m *MockLinkRepository) GetLinkByCode(ctx context.Context, code string) (*models.Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLinkByCode", ctx, code)
	ret0, _ := ret[0].(*models.Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLinkByCode indicates an expected call of GetLinkByCode.
func (mr *MockLinkRepositoryMockRecorder) GetLinkByCode(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLinkByCode", reflect.TypeOf((*MockLinkRepository)(nil).GetLinkByCode), ctx, code)
}

// GetLinkByID mocks base method.
func (m *MockLinkRepository) GetLinkByID(ctx context.Context, id int64) (*models.Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLinkByID", ctx, id)
	ret0, _ := ret[0].(*models.Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLinkByID indicates an expected call of GetLinkByID.
func (mr *MockLinkRepositoryMockRecorder) GetLinkByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLinkByID", reflect.TypeOf((*MockLinkRepository)(nil).GetLinkByID), ctx, id)
}

// ListLinksByUser mocks base method.
func (m *MockLinkRepository) ListLinksByUser(ctx context.Context, userID int64, page, limit int, search string) ([]*models.Link, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLinksByUser", ctx, userID, page, limit, search)
	ret0, _ := ret[0].([]*models.Link)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListLinksByUser indicates an expected call of ListLinksByUser.
func (mr *MockLinkRepositoryMockRecorder) ListLinksByUser(ctx, userID, page, limit, search any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLinksByUser", reflect.TypeOf((*MockLinkRepository)(nil).ListLinksByUser), ctx, userID, page, limit, search)
}

// UpdateLink mocks base method.
func (m *MockLinkRepository) UpdateLink(ctx context.Context, link *models.Link) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLink", ctx, link)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLink indicates an expected call of UpdateLink.
func (mr *MockLinkRepositoryMockRecorder) UpdateLink(ctx, link any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLink", reflect.TypeOf((*MockLinkRepository)(nil).UpdateLink), ctx, link)
}
