// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/chirag3003/go-backend-template/repository (interfaces: ClickRepository)
//
// Generated by this command:
//
//	mockgen -destination=mock/mock_click.go -package=mock github.com/chirag3003/go-backend-template/repository ClickRepository
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	models "github.com/chirag3003/go-backend-template/models"
	repository "github.com/chirag3003/go-backend-template/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockClickRepository is a mock of ClickRepository interface.
type MockClickRepository struct {
	ctrl     *gomock.Controller
	recorder *MockClickRepositoryMockRecorder
	isgomock struct{}
}

// MockClickRepositoryMockRecorder is the mock recorder for MockClickRepository.
type MockClickRepositoryMockRecorder struct {
	mock *MockClickRepository
}

// NewMockClickRepository creates a new mock instance.
func NewMockClickRepository(ctrl *gomock.Controller) *MockClickRepository {
	mock := &MockClickRepository{ctrl: ctrl}
	mock.recorder = &MockClickRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClickRepository) EXPECT() *MockClickRepositoryMockRecorder {
	return m.recorder
}

// CreateClick mocks base method.
func (m *MockClickRepository) CreateClick(ctx context.Context, click *models.ClickEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateClick", ctx, click)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateClick indicates an expected call of CreateClick.
func (mr *MockClickRepositoryMockRecorder) CreateClick(ctx, click any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateClick", reflect.TypeOf((*MockClickRepository)(nil).CreateClick), ctx, click)
}

// GetPreviousSummary mocks base method.
func (m *MockClickRepository) GetPreviousSummary(ctx context.Context, linkID int64) (int64, int64, int64, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPreviousSummary", ctx, linkID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(int64)
	ret3, _ := ret[3].(int64)
	ret4, _ := ret[4].(error)
	return ret0, ret1, ret2, ret3, ret4
}

// GetPreviousSummary indicates an expected call of GetPreviousSummary.
func (mr *MockClickRepositoryMockRecorder) GetPreviousSummary(ctx, linkID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPreviousSummary", reflect.TypeOf((*MockClickRepository)(nil).GetPreviousSummary), ctx, linkID)
}

// GetSummary mocks base method.
func (m *MockClickRepository) GetSummary(ctx context.Context, linkID int64) (int64, int64, int64, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSummary", ctx, linkID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(int64)
	ret3, _ := ret[3].(int64)
	ret4, _ := ret[4].(error)
	return ret0, ret1, ret2, ret3, ret4
}

// GetSummary indicates an expected call of GetSummary.
func (mr *MockClickRepositoryMockRecorder) GetSummary(ctx, linkID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSummary", reflect.TypeOf((*MockClickRepository)(nil).GetSummary), ctx, linkID)
}

// GetTimeSeries mocks base method.
func (m *MockClickRepository) GetTimeSeries(ctx context.Context, linkID int64, window string) ([]repository.TimeSeriesPoint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTimeSeries", ctx, linkID, window)
	ret0, _ := ret[0].([]repository.TimeSeriesPoint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTimeSeries indicates an expected call of GetTimeSeries.
func (mr *MockClickRepositoryMockRecorder) GetTimeSeries(ctx, linkID, window any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTimeSeries", reflect.TypeOf((*MockClickRepository)(nil).GetTimeSeries), ctx, linkID, window)
}

// GetTopBreakdown mocks base method.
func (m *MockClickRepository) GetTopBreakdown(ctx context.Context, linkID int64, field string, limit int) ([]repository.BreakdownRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTopBreakdown", ctx, linkID, field, limit)
	ret0, _ := ret[0].([]repository.BreakdownRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTopBreakdown indicates an expected call of GetTopBreakdown.
func (mr *MockClickRepositoryMockRecorder) GetTopBreakdown(ctx, linkID, field, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTopBreakdown", reflect.TypeOf((*MockClickRepository)(nil).GetTopBreakdown), ctx, linkID, field, limit)
}
